# Generated by Django 4.1.3 on 2022-12-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed_image", models.ImageField(upload_to="")),
                ("feed_image_id", models.IntegerField()),
            ],
        ),
    ]
