# Generated by Django 4.1.3 on 2022-12-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedimage", old_name="feed_image_id", new_name="img_id",
        ),
        migrations.RenameField(
            model_name="feedimage", old_name="feed_image", new_name="img_url",
        ),
    ]
