# Generated by Django 4.1.3 on 2022-12-04 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_rename_feed_image_id_feedimage_img_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedImage',
        ),
    ]
